# Generated by Django 2.0.4 on 2018-05-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=255)),
                ('book_auther', models.CharField(max_length=255)),
                ('book_illust', models.CharField(max_length=255)),
                ('publish_date', models.CharField(max_length=255)),
            ],
        ),
    ]
